[font]
size = 16

[font.normal]
family = "Hack Nerd Font Mono"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.cursor]
cursor = "#ebdbb2"

[window] 
startup_mode = "Maximized"
decorations = "none"

